### ISSUE TITLE
Session API Design

### ISSUE THREAD

**Issue by terrianne-zhang** [redteaming-arena/project-enigma#4]
**Session object:** 

- session_id: unique to every session
- user_id: connects User to Session object
- game_id: connects Game to Session object
- history: list of all messages sent by both user and the model
- completed: boolean flag that represents whether or not the session is active
- create_time: timestamp of when session was started
- outcome: win, loss, or forfeit
- model_id: connects Model to Session object
- shared: boolean to represent whether chat history is shared 
- target: Randomly chosen prompt from Game object contexts
- complete_time: time when Session object has completed = True

**POST: create_game, “/create”, inputs→ [user_id, game_id]**
Create new Session object with unique session ID, user_id = user_id, game_id = game_id, history = [], completed = False, create_time = current time, outcome = None, model_id = randomly selected model_id out of all available model_ids, shared = False, randomly select target_prompt from Game contexts, and set complete_time = None
Return session_id, target_prompt

**POST: chat, “/chat”, inputs → [session_id, user_input, user_id]** 
If session_id does not exist, return 404 Session not found. If session_id does not belong to user_id, return 403 Forbidden. If completed = True, return 403 Forbidden
Append user_input to history in form {“role”: “user”, “content”: user_input}
Query model API from Session object via model_id and append model_output to history in form {“role”: “model”, “content”: model_output}
Find Judge object corresponding to game_id, then use the judge object's judge_type to see if the output of the model matches satisfies the target.
Return model_output, outcome

**POST: share “/share/{session_id}”, inputs → [session_id, user_id]**
If session_id does not exist, return 404 Session not found. If session_id does not belong to user_id, return 403 Forbidden. If completed = False, return 403 Forbidden
Update Session object’s shared field to True
Return session_id, shared

**GET: share “/share/{session_id}”, inputs → [session_id]**
If session_id does not exist, return 404 Session not found. If the Session object is not shared, return 403 Forbidden. 
Return user_id, state, target_phrase, history

**GET: history “/history”, inputs → [user_id]**
Find all Session objects where user_id = user_id and completed = True
If there are no Session objects belonging to this user, return 404 Session not found
Return {session_id, target_phrase, outcome, complete_time - create_time} of all sessions found

**GET: history “/history/{session_id}”, inputs → [user_id, session_id]**
If session_id does not exist, return 404 Session not found
If user_id does not match user_id of Session object, return 403 Forbidden
Return {session_id, target_phrase, outcome, complete_time - create_time, history} of found session

**POST: forfeit “/forfeit”, inputs → [session_id, user_id]**
If session_id does not exist, return 404 Session not found. If user_id does not match user_id of Session object, return 403 Forbidden. If completed = True, return 403 Forbidden.
Update Session object by setting completed = True, complete_time = current_time, outcome = forfeit
Return outcome 

**POST: end_game “/end”, inputs → [session_id, user_id]**
If session_id does not exist, return 404 Session not found. If user_id does not match user_id of Session object, return 403 Forbidden. If completed = True, return 403 Forbidden.
Update Session object by setting completed = True, complete_time = current_time, outcome = loss

**Comment by YihanWang617** [comment]
Some comments copied from the google doc:
- We may need another context attribute to save the game context (For some game types contexts can be different for different sessions of the same game, e.g. the NoRefund game.)
- In  /chat we need to call the judge as specified by the game config. The judge may not always be a string_matching judge.

**Comment by terrianne-zhang** [comment]
Thanks! Made some updates to reflect these points, though will probably come back to this during implementation to add more details
